### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by nanangbro** [laughface809/Baznas_ID#1]
halo ada error saat menginstallnya:

npm ERR! Missing script: "dev"
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:

bagaimana langkah2nya thx

**Comment by laughface809** [comment]
dilihat dari package.json, setelah npm install selesai langsung run:

npm run start

disarankan pakai nodejs versi terbaru

**Comment by nanangbro** [comment]
saya mau buat PR tolong di handle ya @laughface809

**Comment by laughface809** [comment]
Sip
